# KANNEL CONFIGURATION
group = core
admin-port = 13000
smsbox-port = 13001
admin-password = bar
status-password = foo
log-file = "/tmp/kannel.log"
log-level = 0
box-allow-ip = "127.0.0.1;172.*.*.*"

# SMSC FAKE (Simulation Mode)
group = smsc
smsc = fakesmsc
smsc-id = virtual_modem
port = 10000
# All simulated SMS will be written here
file = "/tmp/simulated_sms.log"

# SMSBOX
group = smsbox
bearerbox-host = localhost
sendsms-port = 13013
global-sender = "MamaSafe"

# SENDSMS-USER
group = sendsms-user
username = kannel_user
password = kannel_password
user-deny-ip = ""
user-allow-ip = "*.*.*.*"
